[workspace]
members = [
  "./build",
  "./napi",
  "./napi-derive",
  "./napi-derive-example",
  "./sys",
  "./test_module",
  "./bench",
  "./memory-testing",
  "./serializer",
  "./serializer-wasm",
]

[profile.release]
lto = true
