[package]
edition = "2018"
name = "napi-serializer-wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3"
rkyv = "0.7"
wasm-bindgen = "0.2"
