name: Windows i686

env:
  DEBUG: 'napi:*'

on:
  push:

jobs:
  build_and_test:
    name: stable - windows-latest - i686 - node@14
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          architecture: 'x86'
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: 'Build TypeScript'
        run: yarn build

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: i686-pc-windows-msvc

      - name: Build Tests
        run: |
          yarn --cwd ./examples/napi build-i686 --release
          yarn test -s examples/napi/__test__/values.spec.ts
        env:
          RUST_BACKTRACE: 1
